---
# deploy file for tomcat
 - name: Clean helloworld
   become: yes
   file:
    state: absent
    path: "{{ tomcat_home }}/webapps/{{ item }}"
   with_items:
    - helloworld
    - helloworld.war

 - name: Download helloworld 
   become: yes
   become_user: tomcat
   maven_artifact:
    group_id: com.cts
    artifact_id: HelloWorld
    extension: war  
    repository_url: 'http://54.175.92.214:8081/nexus/content/repositories/snapshots/'
    username: admin
    password: admin123
    version: 0.1-SNAPSHOT
    dest: /tmp/helloworld.war
 
 - name: deploy to Tomcat 
   become: yes
   copy: 
     src: /tmp/helloworld.war 
     dest: "{{ tomcat_home }}/webapps"
     owner: tomcat
     group: tomcat 
     mode: 0755
     remote_src: yes
   notify: restart tomcat
