--- 
 - debug:
    msg: "System {{ inventory_hostname }} has OS {{ ansible_distribution }}"
 - name: Disable root login
   become: yes
   lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
   notify: restart sshd

 - name: Disable password authentication
   become: yes
   lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
   notify: restart sshd
