---
# handlers file for tomcat
 - name: stop tomcat
   become: yes 
   service: name=tomcat state=stopped

 - name: restart tomcat
   become: yes 
   service: name=tomcat state=restarted

 - name: restart iptables
   become: yes 
   service: name=iptables state=restarted
