---
# This will install nagios
- ec2_facts:
  register: ec2_facts
- name: Rename
  action: ec2_tag resource={{ ec2_facts.ansible_facts.ansible_ec2_instance_id }} region='us-east-1' state=present
  args:
     tags:
       "Environment": "{{ env_name }}"

