---
# This role contains common nagios-client that will run on all nodes.
# This will install nagios

- name: install some useful nagios plugins
  yum: name={{ item }} state=absent
  become: yes
  with_items:
   - nagios-nrpe
   - nagios-plugins-ping
   - nagios-plugins-ssh
   - nagios-plugins-http
   - nagios-plugins-swap
   - nagios-plugins-users
   - nagios-plugins-procs
   - nagios-plugins-load
   - nagios-plugins-disk
   - nagios-plugins-all
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

