---
 - name: Gather instance facts
   action: ec2_facts
   register: ec2_facts
   tags: rename
  
 - name: Rename
   local_action: ec2_tag resource={{ ec2_facts.ansible_facts.ansible_ec2_instance_id }} region='us-east-1' state=present
   args:
     tags:
       "SCM_{{ app_name }}": true
   tags: rename

 - name: Launch instance
   ec2: image='ami-b63769a1'
        instance_type='t2.micro'
        keypair='DevOpsCOE-KeyPair'
        instance_tags='{"Environment":"{{ app_name }}_DEV","Class":"{{ app_name }}-mutable","Name":"{{ app_name }} (mutable)"}'
        region='us-east-1'
        aws_zone='us-east-1c'
        group_id='sg-9157bbe0'
        wait=true
        assign_public_ip=yes
        vpc_subnet_id='subnet-f02683aa'
   register: ec2_info
   tags: provision

 - add_host: hostname="{{ item.public_ip }}" grounpname="helloworld,ec2hosts"
   with_items: "{{ ec2_info.instances }}"
   tags: provision

 - name: Wait for instances to listen on port 22
   wait_for:
       state=started
       host="{{ item.public_dns_name }}"
       port=22
   with_items: "{{ ec2_info.instances }}"
   tags: provision    
