---
# This will install nagios
- ec2_remote_facts:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    region: 'us-east-1'
    filters:
      instance-state-name: running
      tag:Environment: ENVPRO
  register: ec2_facts

- name: create the nagios object files
  become: yes
  template: src=helloworld.cfg.j2
            dest=/etc/nagios/ansible-managed/{{ item.public_ip_address + ".cfg" }}
  with_items: "{{ ec2_facts.instances }}"
  notify: restart nagios
