--- 
 - debug:
    msg: "System {{ inventory_hostname }} has OS {{ ansible_distribution }}"
 # This will install nagios
 - ec2_remote_facts:
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    region: 'us-east-1'
    filters:
      instance-state-name: running
      tag:Environment: ENVPRO
   register: ec2_facts

 - name: Configure the haproxy cnf file with hosts
   become: yes
   template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
   notify: restart haproxy


