---
- name: install httpd
  become: yes
  yum: pkg={{ item }} state=present
  with_items:
   - httpd
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: start httpd
  become: yes
  service: name=httpd state=started enabled=yes
