---
# This role contains common nagios-client that will run on all nodes.

- name: install some useful nagios plugins
  yum: name={{ item }} state=present
  become: yes
  with_items:
   - nagios-nrpe
   - nagios-plugins-swap
   - nagios-plugins-users
   - nagios-plugins-procs
   - nagios-plugins-load
   - nagios-plugins-disk
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
