---
# handlers file for common
  - name: restart sshd
    become: yes
    service: name=sshd state=restarted
  - name: Start sshd 
    become: yes
    service: name=sshd state=started enabled=yes 
  - name: restart ntpd
    become: yes
    service: name=ntpd state=restarted
  - name: Start httpd 
    become: yes
    service: name=httpd state=started enabled=yes 
  - name: Start nrpe 
    become: yes
    service: name=nrpe state=started enabled=yes 
