---
# This will install nagios
- name: create the nagios object files
  become: yes
  template: src=helloworld.cfg.j2
            dest=/etc/nagios/ansible-managed/{{ item + ".cfg" }}
  with_items:
    - "{{ groups['helloworld'] }}"
  notify: restart nagios
